const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const sourcePath = path.join(rootDir, 'PRIVACY.md');
const outputPath = path.join(rootDir, 'privacy.html');

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function safeHref(value) {
  const href = String(value).trim();
  if (/^(https?:|mailto:|#)/i.test(href)) return href;
  if (!/^[a-z][a-z0-9+.-]*:/i.test(href)) return href;
  return '#';
}

function renderInline(value) {
  let rendered = escapeHtml(value);
  rendered = rendered.replace(/`([^`]+)`/g, '<code>$1</code>');
  rendered = rendered.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  rendered = rendered.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label, href) => {
    return `<a href="${escapeHtml(safeHref(href))}">${label}</a>`;
  });
  return rendered;
}

function renderMarkdown(markdown) {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n');
  const titleIndex = lines.findIndex(line => /^# /.test(line));
  const title = titleIndex >= 0 ? lines[titleIndex].slice(2).trim() : 'EuroInference Privacy Policy';
  const effectiveDateLine = lines.find(line => /^\*\*Effective date:\*\*/.test(line));
  const effectiveDate = effectiveDateLine
    ? effectiveDateLine.replace(/^\*\*Effective date:\*\*\s*/, '').trim()
    : '';
  const bodyLines = lines.filter((line, index) => index !== titleIndex && line !== effectiveDateLine);
  const output = [];
  let paragraph = [];
  let inList = false;

  function closeList() {
    if (inList) {
      output.push('</ul>');
      inList = false;
    }
  }

  function closeParagraph() {
    if (!paragraph.length) return;
    const content = paragraph.map(line => {
      const hardBreak = /  $/.test(line);
      const cleanLine = hardBreak ? line.slice(0, -2) : line;
      return `${renderInline(cleanLine)}${hardBreak ? '<br>' : ''}`;
    }).join(' ');
    output.push(`<p>${content}</p>`);
    paragraph = [];
  }

  for (const line of bodyLines) {
    if (!line.trim()) {
      closeParagraph();
      closeList();
      continue;
    }

    const heading = line.match(/^(#{2,3})\s+(.+)$/);
    if (heading) {
      closeParagraph();
      closeList();
      const level = heading[1].length;
      const id = heading[2].toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .trim()
        .replace(/\s+/g, '-');
      output.push(`<h${level} id="${id}">${renderInline(heading[2])}</h${level}>`);
      continue;
    }

    const listItem = line.match(/^\s*-\s+(.+)$/);
    if (listItem) {
      closeParagraph();
      if (!inList) {
        output.push('<ul>');
        inList = true;
      }
      output.push(`<li>${renderInline(listItem[1])}</li>`);
      continue;
    }

    closeList();
    paragraph.push(line);
  }

  closeParagraph();
  closeList();

  return { title, effectiveDate, body: output.join('\n') };
}

function buildPage({ title, effectiveDate, body }) {
  const escapedTitle = escapeHtml(title);
  const escapedDate = escapeHtml(effectiveDate);
  return `<!--
  Generated from PRIVACY.md by scripts/build_privacy.js.
  Do not edit this file manually.
  Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0)
  See LICENSE file in the project root for full license text.
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${escapedTitle}.">
  <title>${escapedTitle} | EuroInference</title>
  <link rel="icon" type="image/webp" href="assets/logo_100px.webp">
  <link rel="stylesheet" href="styles.css?v=20260819">
  <script>
    const savedTheme = localStorage.getItem('euroinference-theme');
    document.documentElement.dataset.theme = savedTheme || (window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark');
  </script>
</head>
<body>
  <div class="container policy-container">
    <header class="policy-header">
      <div class="policy-title">
        <a href="index.html" class="brand-logo-link" aria-label="Back to EuroInference dashboard">
          <img src="assets/logo_150px.webp" alt="EuroInference logo" class="brand-logo-img">
        </a>
        <div>
          <p class="policy-kicker">Legal disclosures</p>
          <h1>${escapedTitle}</h1>
          <p class="policy-date">${escapedDate}</p>
        </div>
      </div>
    </header>

    <main class="policy-page glass-panel">
${body}
    </main>

    <footer class="policy-footer">
      <a href="index.html">Back to EuroInference</a>
      <span>Licensed under <a href="LICENSE">AGPL-3.0</a></span>
      <a href="https://github.com/nichu42/euroinference" target="_blank" rel="noopener noreferrer">Project repository</a>
    </footer>
  </div>
</body>
</html>
`;
}

const source = fs.readFileSync(sourcePath, 'utf8');
const rendered = renderMarkdown(source);
fs.writeFileSync(outputPath, buildPage(rendered), 'utf8');
console.log(`Generated ${path.relative(rootDir, outputPath)} from ${path.relative(rootDir, sourcePath)}.`);
